common:
    exp_name: 20news
    arch: RNNAttnClassifier
    batch_size: 64
    
    vocab_size: 17584
    dropout: 0.5
    embed_dim: 300
    hidden_dim: 1024
    label_dim: 2
    num_layers: 1
    bidirectional: True
    
    use_pretrained_emb: True
    update_emb: True
    weight_decay: 0.001
    epoch_num: 20
    lr: 0.0005
    
    dic_path: 'data/20newsgroup/vocab/local_dict.pkl'
    emb_path: 'data/20newsgroup/vocab/local_emb.pkl'
    train_path: 'data/20newsgroup/train_seq.pkl'
    dev_path: 'data/20newsgroup/dev_seq.pkl'
    test_path: 'data/20newsgroup/test_seq.pkl'
    model_name: 'cnn'


