common:
    exp_name: 20news
    arch: RNNAttnClassifier
    batch_size: 64
    
    vocab_size: 29433
    dropout: 0.5
    embed_dim: 300
    hidden_dim: 300
    label_dim: 2
    num_layers: 1
    bidirectional: True
    
    use_pretrained_emb: True
    update_emb: True
    weight_decay: 0.001
    epoch_num: 20
    lr: 0.0005
    
    dic_path: '../../data/20newsgroup_multi/vocab/local_dict_lower.pkl'
    emb_path: '../../data/20newsgroup_multi/vocab/local_emb_lower.pkl'
    train_path: '../../data/20newsgroup_multi/train_seq_lower.pkl'
    dev_path: '../../data/20newsgroup_multi/dev_seq_lower.pkl'
    test_path: '../../data/20newsgroup_multi/test_seq_lower.pkl'
    model_name: 'cnn'


