common:
    exp_name: IMDB_2020
    arch: SimpleAttnClassifier
    batch_size: 256 #64
    
    vocab_size: 63311
    dropout: 0.5
    embed_dim: 300
    hidden_dim: 300
    label_dim: 2
    num_layers: 1
    bidirectional: True
    
    keep_last_model: True
    use_pretrained_emb: False
    update_emb: True
    weight_decay: 0.001
    epoch_num: 20
    lr: 0.01
    
    dic_path: '../../data/IMDB/vocab/local_dict.pkl'
    emb_path: '../../data/IMDB/vocab/local_emb.pkl'
    train_path: '../../data/IMDB/train_seq.pkl'
    dev_path: '../../data/IMDB/dev_seq.pkl'
    test_path: '../../data/IMDB/test_seq.pkl'
    model_name: 'cnn'


