common:
    exp_name: semeval20208
    arch: RNNClassifier
    batch_size: 128
    
    vocab_size: 27115
    dropout: 0.5
    embed_dim: 300
    hidden_dim: 300
    label_dim: 2
    num_layers: 1
    bidirectional: True
    
    use_pretrained_emb: True
    update_emb: True
    weight_decay: 0.001
    epoch_num: 20
    lr: 0.0005
    
    dic_path: '../../data/semeval2010_task8/SemEval2010_task8_all_data/vocab/local_dict_lower.pkl'
    emb_path: '../../data/semeval2010_task8/SemEval2010_task8_all_data/vocab/local_emb_lower.pkl'
    train_path: '../../data/semeval2010_task8/SemEval2010_task8_all_data/train_seq_lower.pkl'
    dev_path: '../../data/semeval2010_task8/SemEval2010_task8_all_data/dev_seq_lower.pkl'
    test_path: '../../data/semeval2010_task8/SemEval2010_task8_all_data/test_seq_lower.pkl'
    model_name: 'rnn'


