common:
    exp_name: sst2_2021
    arch: SimpleClassifier
    batch_size: 1024 #64
    
    vocab_size: 16174
    dropout: 0.5
    embed_dim: 300
    hidden_dim: 300
    label_dim: 2
    num_layers: 1
    bidirectional: True
    
    keep_last_model: True
    use_pretrained_emb: False
    update_emb: True
    weight_decay: 0.001
    epoch_num: 20
    lr: 0.01
    
    dic_path: '../../data/sst/vocab/local_dict.pkl'
    emb_path: '../../data/sst/vocab/local_emb.pkl'
    train_path: '../../data/sst/train_seq.pkl'
    dev_path: '../../data/sst/dev_seq.pkl'
    test_path: '../../data/sst/test_seq.pkl'
    model_name: 'rnn'


