common:
    exp_name: simple_attn_classifier_sst_20200816
    arch: SimpleAttnClassifier
    batch_size: 128
    
    vocab_size: 3482 #16174
    dropout: 0.5
    embed_dim: 300
    hidden_dim: 300
    label_dim: 2
    num_layers: 1
    bidirectional: True
    
    keep_last_model: True
    use_pretrained_emb: True
    update_emb: False
    weight_decay: 0.001
    epoch_num: 30
    lr: 0.05
    
    dic_path: 'data/sst_negation2/vocab/local_dict_lower.pkl'
    emb_path: 'data/sst_negation2/vocab/local_emb_lower.pkl'
    train_path: 'data/sst_negation2/train_seq_lower.pkl'
    dev_path: 'data/sst_negation2/dev_seq_lower.pkl'
    test_path: 'data/sst_negation2/test_seq_lower.pkl'
    model_name: 'rnn'


